import {
  Activity,
  BellRing,
  BotMessageSquare,
  CircleGauge,
  CircleSlash,
  CircleX,
  Clock,
  Gauge,
  HeartPulse,
  History,
  HomeIcon,
  Key,
  LayoutDashboard,
  LogOutIcon,
  MessageCircle,
  Rocket,
  ServerCrash,
  Settings,
  Slash,
  UserIcon,
  SunMoonIcon as SunMoon,
} from "lucide-react";

const iconMap: IconMap = {
  HomeIcon: HomeIcon,
  DashboardIcon: LayoutDashboard,
  UserIcon: UserIcon,
  MessageCircle: MessageCircle,
  BotMessageSquare: BotMessageSquare,
  Slash: Slash,
  CircleSlash: CircleSlash,
  SunMoon: SunMoon,
  Settings: Settings,
  BellRing: BellRing,
  Rocket: Rocket,
  Key: Key,
  Clock: Clock,
  Gauge: Gauge,
  CircleGauge: CircleGauge,
  HeartPulse: HeartPulse,
  Activity: Activity,
  ServerCrash: ServerCrash,
  CircleX: CircleX,
  History: History,
  LogOutIcon: LogOutIcon
};

export default iconMap;
